# Generated by Django 3.2.12 on 2022-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateField(verbose_name='Created at')),
                ('num_pages', models.IntegerField(verbose_name='Num pages')),
                ('genre', models.CharField(max_length=20, verbose_name='genre')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateField(verbose_name='Created at')),
                ('type', models.CharField(choices=[('BULLET', 'Bullet'), ('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('SPORT', 'Sport')], max_length=20, verbose_name='Type')),
                ('publisher', models.CharField(max_length=20, verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
    ]
